let employees = [{ "id": 1, "name": "Lurette", "email": "lhill0@ow.ly", "gender": "Female" },
{ "id": 2, "name": "Cosmo", "email": "cetches1@over-blog.com", "gender": "Polygender" },
{ "id": 3, "name": "Andee", "email": "arosita2@tiny.cc", "gender": "Female" },
{ "id": 4, "name": "Ricki", "email": "rcaen3@spotify.com", "gender": "Female" },
{ "id": 5, "name": "Jdavie", "email": "jperacco4@oaic.gov.au", "gender": "Male" },
{ "id": 6, "name": "Muffin", "email": "mmougel5@sogou.com", "gender": "Genderfluid" },
{ "id": 7, "name": "Buffy", "email": "bdeans6@themeforest.net", "gender": "Non-binary" },
{ "id": 8, "name": "Ranee", "email": "rchardin7@seattletimes.com", "gender": "Female" },
{ "id": 9, "name": "Maxy", "email": "malforde8@t-online.de", "gender": "Male" },
{ "id": 10, "name": "Bengt", "email": "bguillond9@parallels.com", "gender": "Male" },
{ "id": 11, "name": "Walker", "email": "wkinvera@hubpages.com", "gender": "Male" },
{ "id": 12, "name": "Barthel", "email": "btreversb@domainmarket.com", "gender": "Male" },
{ "id": 13, "name": "Isahella", "email": "iashfordc@discuz.net", "gender": "Female" },
{ "id": 14, "name": "Tabbi", "email": "ttarbetd@nydailynews.com", "gender": "Female" },
{ "id": 15, "name": "Karl", "email": "kmulmuraye@sogou.com", "gender": "Male" },
{ "id": 16, "name": "Ax", "email": "adykasf@bloglovin.com", "gender": "Male" },
{ "id": 17, "name": "Durward", "email": "doheffernang@sciencedaily.com", "gender": "Male" },
{ "id": 18, "name": "Nicolas", "email": "nmccullockh@latimes.com", "gender": "Male" },
{ "id": 19, "name": "Horatia", "email": "hperkini@sogou.com", "gender": "Female" },
{ "id": 20, "name": "Eliza", "email": "enekrewsj@sourceforge.net", "gender": "Female" }]

export default employees
