let employees = [{ "id": 1, "name": "Pris", "email": "pweekland0@feedburner.com" },
{ "id": 2, "name": "Griff", "email": "gmcnee1@imageshack.us" },
{ "id": 3, "name": "Adriaens", "email": "alagrange2@blogger.com" },
{ "id": 4, "name": "Hartwell", "email": "hsisselot3@time.com" },
{ "id": 5, "name": "Roman", "email": "rshoutt4@posterous.com" },
{ "id": 6, "name": "Cynthea", "email": "cjerzak5@facebook.com" },
{ "id": 7, "name": "Ulla", "email": "upersich6@phoca.cz" },
{ "id": 8, "name": "Solomon", "email": "slebrom7@dagondesign.com" },
{ "id": 9, "name": "Brit", "email": "bmuggeridge8@topsy.com" },
{ "id": 10, "name": "Jule", "email": "jbrumbie9@amazon.de" },
{ "id": 11, "name": "Grantham", "email": "gpozzoa@prweb.com" },
{ "id": 12, "name": "Glenn", "email": "ghorbathb@epa.gov" },
{ "id": 13, "name": "Terrye", "email": "tebbuttc@blogspot.com" },
{ "id": 14, "name": "Bendix", "email": "bbalkd@multiply.com" },
{ "id": 15, "name": "Jeniece", "email": "jcrope@cornell.edu" },
{ "id": 16, "name": "Rodolphe", "email": "rgirardinif@bloomberg.com" },
{ "id": 17, "name": "Rorie", "email": "rcannellg@acquirethisname.com" },
{ "id": 18, "name": "Brooks", "email": "bdiamenth@hud.gov" },
{ "id": 19, "name": "Lorenza", "email": "lcaskeyi@1und1.de" },
{ "id": 20, "name": "Ollie", "email": "obarsonj@hostgator.com" },
{ "id": 21, "name": "Tanner", "email": "tmacgillek@jigsy.com" },
{ "id": 22, "name": "Dominick", "email": "dsilwoodl@jalbum.net" },
{ "id": 23, "name": "Grove", "email": "gpontainm@bigcartel.com" },
{ "id": 24, "name": "Blanca", "email": "bcantern@cam.ac.uk" },
{ "id": 25, "name": "Stillmann", "email": "srentalllo@patch.com" },
{ "id": 26, "name": "Arni", "email": "apencostp@blogs.com" },
{ "id": 27, "name": "Woodman", "email": "wmicklemq@wikispaces.com" },
{ "id": 28, "name": "Sholom", "email": "smallalieur@alibaba.com" },
{ "id": 29, "name": "Adelina", "email": "aotimonys@un.org" },
{ "id": 30, "name": "Irma", "email": "ipirduet@com.com" },
{ "id": 31, "name": "Maurie", "email": "mtealeu@prlog.org" },
{ "id": 32, "name": "Orazio", "email": "opreedyv@indiegogo.com" },
{ "id": 33, "name": "Roma", "email": "rharkw@adobe.com" },
{ "id": 34, "name": "Stacey", "email": "stomblesonx@histats.com" },
{ "id": 35, "name": "Sonya", "email": "sdanahery@irs.gov" },
{ "id": 36, "name": "Linet", "email": "lbigglestonez@techcrunch.com" },
{ "id": 37, "name": "Reese", "email": "rpeirson10@ft.com" },
{ "id": 38, "name": "Levy", "email": "ltassell11@thetimes.co.uk" },
{ "id": 39, "name": "Emmanuel", "email": "esemeradova12@soundcloud.com" },
{ "id": 40, "name": "Trula", "email": "tmarquiss13@themeforest.net" },
{ "id": 41, "name": "Les", "email": "llarkin14@amazonaws.com" },
{ "id": 42, "name": "Penny", "email": "pdurbin15@tuttocitta.it" },
{ "id": 43, "name": "Ferrell", "email": "fphilipsson16@pagesperso-orange.fr" },
{ "id": 44, "name": "Ardelia", "email": "aberns17@ox.ac.uk" },
{ "id": 45, "name": "Jannelle", "email": "jswannie18@omniture.com" },
{ "id": 46, "name": "Jimmy", "email": "jcullinan19@jugem.jp" },
{ "id": 47, "name": "Kimmi", "email": "kpeery1a@hud.gov" },
{ "id": 48, "name": "Nerte", "email": "ntink1b@behance.net" },
{ "id": 49, "name": "Vinny", "email": "vchat1c@elpais.com" },
{ "id": 50, "name": "Cyndie", "email": "ctilling1d@shop-pro.jp" }]

employees.map(function (emp) {
    console.log(emp.email)
})

/* for (emp of employees) {
    console.log(emp.email)
} */